apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart
  namespace: kickstart
spec:
  selector:
    matchLabels:
      app: kickstart
  template:
    metadata:
      labels:
        app: kickstart
    spec:
      containers:
      - name: kickstart
        image: ghcr.io/ishan-karmakar/kickstart-website:1.0.0
        imagePullPolicy: IfNotPresent