apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart
  namespace: kickstart-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickstart
  template:
    metadata:
      labels:
        app: kickstart
    spec:
      containers:
      - name: kickstart
        image: ghcr.io/ishan-karmakar/kickstart-website:b8edfcb4810349c019a0854eb1fbcbd0f8a21c8c
        ports:
        - containerPort: 80