apiVersion: v1
kind: Service
metadata:
  name: kickstart
  namespace: kickstart-prod
spec:
  selector:
    app: kickstart
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP