apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickstart-website
  template:
    metadata:
      labels:
        app: kickstart-website
    spec:
      containers:
      - image: ghcr.io/ishan-karmakar/kickstart-website
        name: kickstart-website
        ports:
        - containerPort: 80
