apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart
  namespace: kickstart-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickstart
  template:
    metadata:
      labels:
        app: kickstart
    spec:
      containers:
      - name: kickstart
        image: ghcr.io/ishan-karmakar/kickstart-website:latest
        ports:
        - containerPort: 80