resources:
- ../base

images:
- name: lilshan24/kickstart-website
  newTag: latest

patches:
- path: patch.yaml
- target:
    kind: Ingress
    name: kickstart
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: kickstart-staging.everestsummitpm.com