apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart
  annotations:
    keel.sh/policy: force
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kickstart
spec:
  rules:
  - host: kickstart-staging.everestsummitpm.com