name: Deploy Website to ArgoCD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: docker build -t ghcr.io/ishan_karmakar/kickstart-website:${{ github.sha }} .
      - name: Push
        run: docker push ghcr.io/ishan_karmakar/kickstart-website:${{ github.sha }}
